### ISSUE TITLE
Silent notifications

### ISSUE THREAD

**Issue by SebastianStehle** [notifo-io/sdk-xamarin#3]
Some notifications are marked as silent, which means they should not been rendered but just made available in the SDK.

**Comment by sanyandreichuk** [comment]
Implemented. We are handling silent notifications in firebase settings

![chrome_2022-02-15_12-10-19](https://user-images.githubusercontent.com/8818052/154040379-f36032cc-fa7e-4712-ab03-c54edbf4e4a1.png)
